config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :articles, only: [:index]
  resources :users, :except => [:index]
  resources :groups do
    resources :articles, except: [:index] do
      resources :tags, :only => [:create]
    end
  end

  resources :memberships, only: [:create, :show]

  resources :tags, :only => [:show]

  resources :footnotes, :except => [:index, :show]

  post 'favorite_article' => 'favorites#create'
  delete 'unfavorite_article' => 'favorites#destroy'
  put 'publish_article' => 'articles#publish'
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :group
  belongs_to :writer, class_name: "User"
  has_many :designations
  has_many :edits
  has_many :favorites
  has_many :tags, through: :designations

  validates :title, :body, presence: true

  def is_favorited?(current_user)
    !!self.favorites.find_by(user_id: current_user.id)
  end

  def self.search(search)
    where("LOWER(title) LIKE LOWER(?)", "%#{search}%") || where("LOWER(body) LIKE LOWER(?)", "%#{search}%")
  end

  def self.published?
    self.published
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

include ApplicationHelper

  def index
    @articles = Article.all
    if params[:search]
      search = params[:search].downcase
      capitalize_search = search.capitalize
      @articles = Article.search(capitalize_search).order("created_at DESC")
   else
      @articles = Article.all.order('created_at DESC')
    end
  end

  def new
    @article = Article.new
    @group = Group.find(params[:group_id])
    @article.writer_id = current_user.id
    @article.group_id = @group.id
  end

  def create
    @article = Article.new(article_params)
    @group = Group.find(params[:group_id])
    @article.writer_id = current_user.id
    @article.group_id = @group.id
    if @article.save
       render '/articles/show'
    else
      flash[:errors] = @article.errors.full_messages
      redirect_to @group
    end
  end

  def show
    @tag = Tag.new
    @article = Article.find_by(id: params[:id])
    @tags = @article.tags
    @user = @article.writer.username
    @group = Group.find_by(id: params[:group_id])

    if @article
      render '/articles/show'
    else
      redirect_to @group
    end
  end

  def edit
    @article = Article.find_by(id: params[:id])
    @group = @article.group
  end

  def update
    @article = Article.find(params[:id])
    @group = @article.group

    if @article.update(article_params)
      redirect_to [@group, @article]
    else
      render 'edit'
    end
  end

  def publish
    @article = Article.find_by(id: params[:article_id])
    @group = @article.group
    if @article
      @article.published = true
      @article.save
      if request.xhr?
        render partial: "/articles/article", locals: {article: @article}
      end
    else
      redirect_to root_path
    end

  end

  def destroy
    @article = Article.find_by(id: params[:id])
    @article.destroy
    redirect_to @article.group
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper



end

app/views/articles/_article.html.erb
  <p><%= link_to article.title, [@group, article] %></p>

app/views/articles/_publish.html.erb
<%= form_tag publish_article_path, {:class => 'publish'} do %>
	<%= hidden_field_tag(:article_id, unpublished.id) %>
	<%= radio_button_tag(:published, true)%>	
	<%= label_tag(:article, " Publish?") %>
<% end %>

app/views/articles/_search.html.erb
<% form_tag articles_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<%= form_for [@group, @article] do |f| %>
 
  <div>
    <%= f.label :title %>:<br>
    <%= f.text_field :title, 
                     class: "form-control" %>
  </div>
 
  <div>
    <%= f.label :body %>:<br>
    <%= f.text_area :body, 
                    class: "form-control",
                    rows: "15",
                    id: "comment" %>
  </div>
 
  <div>
    <%= f.submit class: "btn btn-primary" %>
  </div>
 
<% end %>

app/views/articles/index.html.erb
<h2>Articles: </h2>

<%= form_tag(articles_path, :method => "get", id: "search-form") do %>
 <div class="form-inline">
 <%= text_field_tag :search, params[:search], placeholder: "Search Articles", class: "form-control input-md" %>
 <%= submit_tag "Search", class: "btn btn-primary" %>
 <% end %>
</div>
<br>

<% @articles.each do |article| %>
	<% if article.published? %>
		<div><%= link_to article.title, "/groups/#{article.group_id}/articles/#{article.id}" %></div>
	<% end %>
<% end %>

app/views/articles/new.html.erb
<h3>Add a new article:</h3>

<%= form_for [@group, @article] do |f| %>
  <%= f.label :title %>:
    <%= f.text_field :title, class: "form-control" %><br>
  <%= f.label :body %>:
    <%= f.text_area :body, class: "form-control", rows: "15", id: "comment" %><br>
  <%= f.submit "submit", class: "btn btn-primary"   %>
<% end %>

app/views/articles/show.html.erb
<section class="title-and-bookmark">
  <div><h2 class="article-title"><%= @article.title %></h2></div>
  <% if logged_in? &&  @article.published? %>
    <div class="bookmark-container"><%= render partial:'favorites/favorite_form' %></div>
  <%end%>
</section>


<br/>
<div><p class="article-body"><%= @article.body %><p></div>
<div id="article-author">Added by:</div>
<div><%= link_to @article.writer.username,
     user_path(@article.writer_id) %></div>

<% if logged_in? %>
<% if  current_user.id == @article.writer_id %>
    <%= link_to 'Destroy',
      group_article_path(@group, @article),
      method: :delete,
    data: { confirm: 'Last chance, still want to delete?'} %>
  | <%= link_to 'Edit',
      edit_group_article_path(@group, @article) %>
<% end %>
<% end %>

<div>
<%= link_to 'Back to Group', @group %>
</div>

<div id="article-show-tags-container">
  <% if logged_in? %>
    <%= render '/tags/new_tag' %>
  <% end %>
  <%= render '/tags/tags' %>
</div>