config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :articles, only: [:index]
  resources :users, :except => [:index]
  resources :groups do
    resources :articles, except: [:index] do
      resources :tags, :only => [:create]
    end
  end

  resources :memberships, only: [:create, :show]

  resources :tags, :only => [:show]

  resources :footnotes, :except => [:index, :show]

  post 'favorite_article' => 'favorites#create'
  delete 'unfavorite_article' => 'favorites#destroy'
  put 'publish_article' => 'articles#publish'
  root 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :memberships
  has_many :articles
  has_many :users, through: :memberships

  validates :name, uniqueness: true
  validates :name, presence: true

   def self.search(search)
     where("LOWER(name) LIKE LOWER(?)", "%#{search}%")
   end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
include ApplicationHelper

  def index
    @groups = Group.all
    if params[:search]
      search = params[:search].downcase
      capitalize_search = search.capitalize
      @groups = Group.search(capitalize_search).order("created_at DESC")
   else
     @groups = Group.all.order('created_at DESC')
    end
  end

  def new
    redirect_to_login
    @group = Group.new
  end

  def create
    capitalize_group = params[:group][:name].downcase.capitalize
    @group = Group.new(name: capitalize_group)
    if @group.save
      @membership = Membership.create( user_id: current_user.id,
                                       role: "admin",
                                       group_id: @group.id )
      redirect_to @group
    else
      flash[:error] = @group.errors.full_messages
      redirect_to '/groups/new'
    end
  end

  def show
    @group = Group.find_by(id: params[:id])
    if @group
      @group_name = @group.name
      @users = @group.memberships
      @articles = @group.articles
      @published = @articles.where(published: true)
      @unpublished = @articles.where(published: false)
      render '/groups/show'
    else
      redirect_to '/'
    end
  end

  def edit
  end

  def destroy
    @group = Group.find_by(id: params[:id])
    @group.delete
    redirect_to '/groups'
  end

private

  def group_params
    params.require(:group).permit(:name)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper

  def admin?
    !check_for_admin.empty?
  end

  def check_for_admin
    @group.memberships.select do |group|
      group.role == "admin" && group.user.id == current_user.id
    end
  end

end

app/views/groups/index.html.erb
<h2>Groups:</h2>

<%= form_tag(groups_path, :method => "get", id: "search-form") do %>
 <div class="form-inline">
 <%= text_field_tag :search, params[:search], placeholder: "Search Groups", class: "form-control input-md" %>
 <%= submit_tag "Search", class: "btn btn-primary" %>
 <% end %>

<div id="link-ord">
  <% if @groups %>
    <% @groups.each do |group|%>
      <div><%= link_to group.name, group_path(group) %></div>
    <%end%>
  <%end%>
</div>

app/views/groups/new.html.erb
<% provide(:title, '| Create a Group') %>
<h3 class="create-group">Create a Group:</h3>
<div>
<% if flash %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value.first %></div>
      <% end %>

<% end %>
</div>

<div class="row form-inline">
  <div class="col-md-6 ">
    <%= form_for(@group) do |f| %>
      <%= f.text_field :name, placeholder: "group name", class: "form-control input-md" %>
      <%= f.submit "create", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, '| Groups') %>

<h1><%= @group_name %></h1>

<% if logged_in? %>
  <% if admin? %>
    <%= link_to 'delete group', group_path(@group),
            method: :delete,
            data: { confirm: 'Are you sure?'} %>
    | <%= link_to 'add article', new_group_article_path(@group) %>
  <% elsif member_already? %>
    <p><%= link_to 'add article', new_group_article_path(@group) %></p>
  <% end %>
<% end %>

<h3>Users:</h3>
<% @users.each do |member| %>
  <p><%= link_to member.user.username, user_path(member.user) %>, <%= member.role %></p>
<%end%>

<% if logged_in? %>
  <% if admin? %>
    <% @unpublished.each do |unpublished| %>
    <div class="unpublished-article">
      <p ><%= link_to unpublished.title, [@group, unpublished] %>, <%= render partial: '/articles/publish', locals: {unpublished: unpublished } %></p> </div>
    <% end %>
  <% end %>
<% end %>

<h3>Articles:</h3>
<div class="article-published" >
<% @published.each do |article| %>
  <p><%= link_to article.title, [@group, article] %></p>
<% end %>
</div>

<% if flash %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<% end %>

<% if logged_in? && !member_already? %>
  <%= form_tag(memberships_path, method: "post") do %>
    <%= hidden_field_tag(:group_id, value=@group.id)%>
    <%= submit_tag "Join", class: "btn btn-secondary" %>
  <% end %>
<% end %>