config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :articles, only: [:index]
  resources :users, :except => [:index]
  resources :groups do
    resources :articles, except: [:index] do
      resources :tags, :only => [:create]
    end
  end

  resources :memberships, only: [:create, :show]

  resources :tags, :only => [:show]

  resources :footnotes, :except => [:index, :show]

  post 'favorite_article' => 'favorites#create'
  delete 'unfavorite_article' => 'favorites#destroy'
  put 'publish_article' => 'articles#publish'
  root 'welcome#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :designations
  has_many :articles, through: :designations

  validates :label, presence: true

  def new_valid_tag?(article, label)
    if label.present?
      @tag = Tag.find_or_create_by(label: label)
      @tag.valid_tag?(article)
    end
  end

  def valid_tag?(article)
    if self.valid?
      @designation = Designation.create(tag_id: self.id, article_id: article.id)
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by(id: params[:id])
    if params[:search]
      search = params[:search].downcase
      capitalize_search = search.capitalize
      @articles = @tag.articles.search(capitalize_search).order("created_at DESC")
    else
      @articles = @tag.articles.order('created_at DESC')
    end
    render '/tags/show'
  end

  def create
    @tag = Tag.new
    @article = Article.find_by(id: params[:article_id])
    @group = @article.group
    @tags = @article.tags
    if @tag.new_valid_tag?(@article, params[:label])
      render partial: 'tags/tags'
    else
      flash[:error] = @tag.errors.full_messages
      render :json => {}
    end

  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_new_tag.html.erb
<div id="new-tag-form">

  <%= form_tag("/groups/#{@group.id}/articles/#{@article.id}/tags", method: "post", id: "new-tag-form") do %>
    <%= hidden_field_tag(:article_id, value=@article.id)%>
    <%= text_field_tag :label, params[:label], placeholder: "tag", class: "form-control input-md tag-field", id: "tag-form-field" %>
    <%= submit_tag "create tag", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/tags/_tags.html.erb
<div class="all-tags">
  <% if @tags %>
    <% @tags.each do |tag| %>
      <span class="article-show-tag"> <%= link_to tag.label, tag_path(tag) %> </span>
    <% end %>
  <% end %>
</div>

app/views/tags/create.js.erb
<% @tags.each do |tag| %>
  <span class="article-show-tag"> <%= link_to tag.label, tag_path(tag) %> </span>
<% end %>

app/views/tags/index.html.erb
<section class="title-and-bookmark">
  <div><h2 class="article-title">Tags</h2></div>
</section>


<%= form_tag(tags_path, :method => "get", id: "search-form") do %>
 <div class="form-inline">
 <%= text_field_tag :search, params[:search], placeholder: "Search Groups", class: "form-control input-md" %>
 <%= submit_tag "Search", class: "btn btn-primary" %>
 <% end %>

<div id="link-ord">
<% @tags.each do |tag| %>
	<div><%= link_to tag.label, tag %></div>	
<% end %>
	

app/views/tags/show.html.erb
<h1><%=@tag.label%> </h1>

<%= form_tag(tag_path, :method => "get", id: "search-form") do %>
 <div class="form-inline">
 <%= text_field_tag :search, params[:search], placeholder: "Search Articles", class: "form-control input-md" %>
 <%= submit_tag "Search", class: "btn btn-primary" %>
 <% end %>
</div>

<div>
  <h3>Articles:</h3>
  <ul>
  <% @articles.each do |article| %>
    <div class="tag-show-article-titles"><h4><%= link_to article.title, group_article_path(article.group, article) %></h4></div>
  <% end %>
  </ul>
</div>